### ISSUE TITLE
Can you please also include web template with the project

### ISSUE THREAD

**Issue by seeramzan** [Devskiller/jfairy#109]
Hi,

Could you please also include the web template (https://devskiller.com/datafairy/) with the liberary. I want to host to my local machine with customization according to my project.

**Comment by jkubrynski** [comment]
Hi @seeramzan ,

the library is open-source project, however the online version is currently not available. I'm not sure we'll share it on github currently.

Best,
Jakub

**Comment by seeramzan** [comment]
@jkubrynski thanks for your kind reply. If i want to take web part what is the procedure please.
