### ISSUE TITLE
Illegal Characters in E-Mail addresses

### ISSUE THREAD

**Issue by realulim** [Devskiller/jfairy#120]
Generated names should not be used verbatim in the construction of email addresses, because they can contain characters that are not allowed in email addresses.

Example: "Hugo Groß" leads to the German ß umlaut appearing in his email address.

**Comment by realulim** [comment]
Oops, I see this is already fixed, but hasn't been released. Perhaps someone could make a release, if the project is still active.

**Comment by mariuszs** [comment]
@realulim Please check version 0.6.3. Cheers.

**Comment by realulim** [comment]
@mariuszs Great, thank you. Is this going to land in mvnrepository.com or should I take it off Github?

**Comment by mariuszs** [comment]
@realulim something is broken with releasing to maven central. I will let you know when it is fixed.

**Comment by mariuszs** [comment]
@realulim It is already in Maven Central, please let me know if it is ok :)

https://repo1.maven.org/maven2/com/devskiller/jfairy/0.6.3/

**Comment by realulim** [comment]
Perfect, thank you! JFairy is one of the most useful tools I know.
