### ISSUE TITLE
DateProducerSpec fails on Travis

### ISSUE THREAD

**Issue by szpak** [Devskiller/jfairy#22]
`eu.codearte.jfairy.producer.DateProducerSpec` fails on Travis. It happened in the [past](https://travis-ci.org/Codearte/jfairy/jobs/39034145#L442), but was silently ignored thanks to the `ingoreFailures` flag in build.gradle... The problem is pretty visible in [notIgnoreFailingTest](https://github.com/Codearte/jfairy/tree/topic/notIgnoreFailingTests) branch (see [Travis](https://travis-ci.org/Codearte/jfairy/builds/49902454)).

@mariuszs any idea?

**Comment by benmccann** [comment]
If fails for me locally as well

>io.codearte.jfairy.producer.DateProducerSpec > should generate date between years 2010 - 2010 FAILED
    org.spockframework.runtime.SpockComparisonFailure at DateProducerSpec.groovy:82
io.codearte.jfairy.FairyFrSpec > Should create French name FAILED
    org.spockframework.runtime.SpockComparisonFailure at FairyFrSpec.groovy:15

**Comment by mariuszs** [comment]
cannot reproduce, please reopen if this bug still exist
