### ISSUE TITLE
End of support for Java 7?

### ISSUE THREAD

**Issue by szpak** [Devskiller/jfairy#23]
Oracle [plans](http://www.oracle.com/technetwork/java/eol-135779.html) to end releasing public updates for Java 7 in April 2015. We are considering to end support for Java 7 in jFairy along with it (jFairy versions released after that time would require Java 8+).

If you (as a jFairy user) have a good argument to keep support for Java 7 a little bit longer please say it in that issue.

**Comment by mariuszs** [comment]
1. jFairy is useful also on Android Platform (JDK 1.7 only)

**Comment by szpak** [comment]
Good point. Anyway with [retrolambda[(https://github.com/orfjackal/retrolambda) it can be mitigated.

**Comment by mariuszs** [comment]
> Does not backport Java 8 language features other than lambda expressions.

I dont think this is enough for us.

**Comment by tpischke** [comment]
I would love to see added support for JDK 8 features, especially JDK 8 DateTime.  We no longer use anything < Java 8 for development.  Considering the huge advantages of JDK 8, and the end of life status of Java 7, I would love to see JDK 8 features embraced and java 7 support dropped.

This would also help me decide between jFairy and java-faker ;)

**Comment by mariuszs** [comment]
Ok, done :)

**Comment by szpak** [comment]
2,5 years later :)
