### ISSUE TITLE
Too much dependencies

### ISSUE THREAD

**Issue by dungdm93** [Devskiller/jfairy#61]
I think those dependencies are to much, and a lot of them are no need for end-user.
![dependences](https://cloud.githubusercontent.com/assets/6848311/16139060/26e1ba08-346e-11e6-90dc-fa6eb51b2726.png)
I suggest that you consider to **remove** or **change it to optional**, like:

``` xml
<dependency>
    <groupId>org.yaml</groupId>
    <artifactId>snakeyaml</artifactId>
    <version>[1.9,2.0)</version>
    <optional>true</optional>
</dependency>
```

**Comment by pnowy** [comment]
Similar like @dungdm93  I also suggest to change `snakeyaml` range dependency to the specific version. It's not a good approach for public libraries and in our project we had to exclude `snakeyaml` because the maven was trying to download for some reasons the 1.19-SNAPSHOT of `snakeyaml`.
