### ISSUE TITLE
Build fails when on release tag and no keys are configured

### ISSUE THREAD

**Issue by szpak** [Devskiller/jfairy#79]
As reported in #78. `./gradlew build` fails with:

```
* Where:
Build file '/home/foo/code/jfairy/build.gradle' line: 114

* What went wrong:
signing.keyId and signing.secretKeyRingFile has to be configured (e.g. in ~/.gradle/gradle.properties)
```

if the latest commit is tagged with a release tag. It can be confusing for external contributors.

As a workaround `-x sign` can be used.

**Comment by mariuszs** [comment]
closing, because all gradle issues are fixed now
