### ISSUE TITLE
Wrong getAddressLine1 format for de(-DE)

### ISSUE THREAD

**Issue by Taig** [Devskiller/jfairy#91]
Expected: `$street $number`
Actual: `$number $street`

**Comment by rweisleder** [comment]
This issue should be resolved with the next release. See commit 164fb92e9c277639c66aa520cead5ca8323ed8d4 and [DeAddressSpec](https://github.com/Devskiller/jfairy/blob/master/src/test/groovy/io/codearte/jfairy/producer/person/locale/de/DeAddressSpec.groovy).
